# Generated by Django 2.2.1 on 2019-06-03 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k_move_left', models.CharField(default='a', max_length=20)),
                ('k_move_right', models.CharField(default='d', max_length=20)),
                ('k_move_forward', models.CharField(default='w', max_length=20)),
                ('k_move_backward', models.CharField(default='s', max_length=20)),
                ('k_reload', models.CharField(default='r', max_length=20)),
                ('k_movemode2', models.CharField(default='v', max_length=20)),
                ('k_firemode', models.CharField(default='x', max_length=20)),
                ('ingame_name', models.CharField(default='Jack', max_length=20)),
                ('screen_quality', models.IntegerField(default=1)),
                ('lazy_weapon', models.DecimalField(decimal_places=1, default=1.0, max_digits=2)),
                ('brightness', models.DecimalField(decimal_places=1, default=1.0, max_digits=2)),
                ('model', models.CharField(choices=[('hero', 'objects/characters/pmodels/hero/hero_mp.cgf'), ('merc_rear', 'objects/characters/mercenaries/merc_scout/merc_scout_mp.cgf'), ('merc_rear', 'objects/characters/mercenaries/merc_rear/merc_rear_mp.cgf'), ('evil_worker', 'bbjects/characters/workers/evil_worker/evil_worker_MP.cgf'), ('mertz', 'objects/characters/pmodels/story_characters/mertz/mertz_mp.cgf')], default='objects/characters/pmodels/hero/hero_mp.cgf', max_length=200)),
                ('player_skin', models.IntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
