# Generated by Django 2.2.1 on 2019-05-30 12:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20190530_1239'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='usersettings',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='usersettings',
            unique_together={('username', 'order')},
        ),
    ]
