# Generated by Django 2.2.1 on 2019-05-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190530_1317'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersettings',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='usersettings',
            unique_together=set(),
        ),
    ]
