# Generated by Django 2.2.1 on 2019-05-30 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190530_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='order',
        ),
    ]
