# Generated by Django 2.2.1 on 2019-06-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190531_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='K_FIREMODE',
            field=models.CharField(default='x', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='K_MOVEMODE2',
            field=models.CharField(default='v', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='K_MOVE_BACKWARD',
            field=models.CharField(default='s', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='K_MOVE_FORWARD',
            field=models.CharField(default='w', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='K_MOVE_LEFT',
            field=models.CharField(default='a', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='K_MOVE_RIGHT',
            field=models.CharField(default='d', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='K_RELOAD',
            field=models.CharField(default='r', max_length=20),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='ingame_name',
            field=models.CharField(default='Jack', max_length=20),
        ),
    ]
