# Generated by Django 2.2.1 on 2019-06-02 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_auto_20190602_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchfrags',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match', to='matches.Matches'),
        ),
    ]
