# Generated by Django 2.2.1 on 2019-06-02 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_auto_20190602_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchfrags',
            name='killer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_frags_killer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchfrags',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_frags', to='matches.Matches'),
        ),
        migrations.AlterField(
            model_name='matchfrags',
            name='victim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='match_frags_victim', to=settings.AUTH_USER_MODEL),
        ),
    ]
