# Generated by Django 2.2.1 on 2019-06-02 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_auto_20190602_1901'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matchfrags',
            old_name='match',
            new_name='match_id',
        ),
    ]
