# Generated by Django 2.2.1 on 2019-06-03 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSettings',
        ),
    ]
